server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "URL для подключения к БД. Пример ниже:"
    #"jdbc:postgresql://localhost:5432/petproject?currentSchema=public"
    username: [Пользователь БД]
    password: [Пароль пользователя БД]
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.yaml
telegram:
  bot:
    token: [ВАШ_ТОКЕН_ТУТ]
    name: [ИМЯ_ВАШЕГО_БОТА]
